[tools]
pre-commit = "latest"
python = "3.13"
trivy = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[env]
APP_REPO = 'devops-test-app'
GITOPS_REPO = 'devops-test-app-gitops'

[hooks]
enter = "bash ./scripts/setup_project"
